// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMaxDebtProject.Data;

#nullable disable

namespace MvcMaxDebtProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824074604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcMaxDebtProject.Models.MusteriFatura", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FATURA_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FATURA_TUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MUSTERI_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ODEME_TARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MUSTERI_ID");

                    b.ToTable("MUSTERI_FATURA_TABLE", (string)null);
                });

            modelBuilder.Entity("MvcMaxDebtProject.Models.MusteriTanim", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("UNVAN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("MUSTERI_TANIM_TABLE", (string)null);
                });

            modelBuilder.Entity("MvcMaxDebtProject.Models.MusteriFatura", b =>
                {
                    b.HasOne("MvcMaxDebtProject.Models.MusteriTanim", "MusteriTanim")
                        .WithMany()
                        .HasForeignKey("MUSTERI_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusteriTanim");
                });
#pragma warning restore 612, 618
        }
    }
}
