// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMaxDebtProject.Data;

#nullable disable

namespace MvcMaxDebtProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824113615_UpdateTableSchema")]
    partial class UpdateTableSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcMaxDebtProject.Models.MusteriFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("FATURA_TARIHI");

                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FATURA_TUTARI");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("MUSTERI_ID");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("ODEME_TARIHI");

                    b.HasKey("Id");

                    b.ToTable("MUSTERI_FATURA_TABLE", (string)null);
                });

            modelBuilder.Entity("MvcMaxDebtProject.Models.MusteriTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UNVAN");

                    b.HasKey("Id");

                    b.ToTable("MUSTERI_TANIM_TABLE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
